---
- hosts: ali_q_cloud
  remote_user: root
  tasks:
    - name: docker login
      docker_login:
        username: "{{docker_user}}"
        password: "{{docker_passwd}}"
        registry: docker.haihui.site
    - name: deploy web
      docker_container:
        name: web
        image: docker.haihui.site/go-gsc:{{tag}}
        state: started
        pull: true
        restart: true
        restart_policy: always
        env:
          wxAppId: "{{wxAppId}}"
          wxappSecret: "{{wxappSecret}}"
          listenAddr: "{{listenAddr}}"
          mysqlDSN: "{{mysqlDSN}}"
        published_ports:
          - "8080:8080"
